# This file was generated by GoReleaser. DO NOT EDIT.
cask "node-alias" do
  name "node-alias"
  desc "A smart alias for all node package managers"
  homepage "https://github.com/jcwillox/node-alias"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "node-alias"
  bash_completion "completions/node-alias.bash"
  zsh_completion "completions/node-alias.zsh"
  fish_completion "completions/node-alias.fish"

  on_macos do
    on_intel do
      url "https://github.com/jcwillox/node-alias/releases/download/v#{version}/node_alias_#{version}_darwin_amd64.tar.gz"
      sha256 "50f8bafe3b5f208d6b0078a436bc00b43338819c79cf3783398e7378eba73f48"
    end
    on_arm do
      url "https://github.com/jcwillox/node-alias/releases/download/v#{version}/node_alias_#{version}_darwin_arm64.tar.gz"
      sha256 "400922d7c99314dabb97249beb8e82c7984da322a7d24f5787a62709c97a33cb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jcwillox/node-alias/releases/download/v#{version}/node_alias_#{version}_linux_amd64.tar.gz"
      sha256 "f6aa3182b68782a5061565473bec4de271641ba64fa90f649d6a16cb53e9e7b1"
    end
    on_arm do
      url "https://github.com/jcwillox/node-alias/releases/download/v#{version}/node_alias_#{version}_linux_arm64.tar.gz"
      sha256 "76b3d3ea063dd7865352c4429fae37b0fe9c5b257378caf2e61aafd2b91ac58a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/node-alias"]
    end
  end

  # No zap stanza required
end
